#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
	# Remove lease database
	rm -f /var/lib/dhcp/dhclient*.leases
	rm -f /var/lib/dhcp/dhclient*.lease

	# Try to remove directory
	if [ -d /var/lib/dhcp ]; then
		rmdir --ignore-fail-on-non-empty /var/lib/dhcp/
	fi

	rmdir --ignore-fail-on-non-empty /etc/dhcp

fi

# https://bugs.debian.org/1102626
if dpkg-maintscript-helper supports mv_conffile; then
dpkg-maintscript-helper mv_conffile \
    /etc/apparmor.d/sbin.dhclient /etc/apparmor.d/usr.sbin.dhclient 4.4.3-P1-7~ -- "$@"
fi

#DEBHELPER#
